country_food_map = {
    "China": {"flag": "cn", "category": "Asian"},
    "Japan": {"flag": "jp", "category": "Asian"},
    "South Korea": {"flag": "kr", "category": "Asian"},
    "Mongolia": {"flag": "mn", "category": "Asian"},
    "Nepal": {"flag": "np", "category": "Asian"},
    "Bangladesh": {"flag": "bd", "category": "Asian"},

    "Thailand": {"flag": "th", "category": "Southeast Asian"},
    "Vietnam": {"flag": "vn", "category": "Southeast Asian"},
    "Indonesia": {"flag": "id", "category": "Southeast Asian"},
    "Malaysia": {"flag": "my", "category": "Southeast Asian"},
    "Philippines": {"flag": "ph", "category": "Southeast Asian"},
    "Singapore": {"flag": "sg", "category": "Southeast Asian"},
    "Cambodia": {"flag": "kh", "category": "Southeast Asian"},
    "Laos": {"flag": "la", "category": "Southeast Asian"},
    "Myanmar": {"flag": "mm", "category": "Southeast Asian"},
    "Timor-Leste": {"flag": "tl", "category": "Southeast Asian"},

    "India": {"flag": "in", "category": "Indian"},
    "Pakistan": {"flag": "pk", "category": "Indian"},
    "Sri Lanka": {"flag": "lk", "category": "Indian"},
    "Nepal": {"flag": "np", "category": "Indian"},
    "Bhutan": {"flag": "bt", "category": "Indian"},
    "Bangladesh": {"flag": "bd", "category": "Indian"},

    "Lebanon": {"flag": "lb", "category": "Middle Eastern"},
    "Turkey": {"flag": "tr", "category": "Middle Eastern"},
    "Iran": {"flag": "ir", "category": "Middle Eastern"},
    "Israel": {"flag": "il", "category": "Middle Eastern"},
    "Saudi Arabia": {"flag": "sa", "category": "Middle Eastern"},
    "Syria": {"flag": "sy", "category": "Middle Eastern"},
    "Jordan": {"flag": "jo", "category": "Middle Eastern"},
    "United Arab Emirates": {"flag": "ae", "category": "Middle Eastern"},

    "Greece": {"flag": "gr", "category": "Mediterranean"},
    "Italy": {"flag": "it", "category": "Mediterranean"},
    "Spain": {"flag": "es", "category": "Mediterranean"},
    "Morocco": {"flag": "ma", "category": "Mediterranean"},
    "Tunisia": {"flag": "tn", "category": "Mediterranean"},
    "Algeria": {"flag": "dz", "category": "Mediterranean"},
    "Egypt": {"flag": "eg", "category": "Mediterranean"},

    "France": {"flag": "fr", "category": "Western / European"},
    "United Kingdom": {"flag": "gb", "category": "Western / European"},
    "uk": {"flag": "gb", "category": "Western / European"},
    "UK": {"flag": "gb", "category": "Western / European"},
    "Germany": {"flag": "de", "category": "Western / European"},
    "Netherlands": {"flag": "nl", "category": "Western / European"},
    "Belgium": {"flag": "be", "category": "Western / European"},
    "Switzerland": {"flag": "ch", "category": "Western / European"},
    "Austria": {"flag": "at", "category": "Western / European"},
    "Portugal": {"flag": "pt", "category": "Western / European"},

    "United States": {"flag": "us", "category": "American"},
    "America": {"flag": "us", "category": "American"},
    "usa": {"flag": "us", "category": "American"},
    "Mexico": {"flag": "mx", "category": "American"},
    "Puerto Rico": {"flag": "pr", "category": "American"},

    "Brazil": {"flag": "br", "category": "Latin American"},
    "Argentina": {"flag": "ar", "category": "Latin American"},
    "Peru": {"flag": "pe", "category": "Latin American"},
    "Colombia": {"flag": "co", "category": "Latin American"},
    "Chile": {"flag": "cl", "category": "Latin American"},
    "Cuba": {"flag": "cu", "category": "Latin American"},
    "Dominican Republic": {"flag": "do", "category": "Latin American"},

    "Ethiopia": {"flag": "et", "category": "African"},
    "Nigeria": {"flag": "ng", "category": "African"},
    "Kenya": {"flag": "ke", "category": "African"},
    "South Africa": {"flag": "za", "category": "African"},
    "Senegal": {"flag": "sn", "category": "African"},
    "Angola": {"flag": "ao", "category": "African"},
    "Tanzania": {"flag": "tz", "category": "African"},

    "Jamaica": {"flag": "jm", "category": "Caribbean"},
    "Haiti": {"flag": "ht", "category": "Caribbean"},
    "Trinidad and Tobago": {"flag": "tt", "category": "Caribbean"},
    "Bahamas": {"flag": "bs", "category": "Caribbean"},
    "Barbados": {"flag": "bb", "category": "Caribbean"},

    "Australia": {"flag": "au", "category": "Oceanic"},
    "New Zealand": {"flag": "nz", "category": "Oceanic"},
    "Fiji": {"flag": "fj", "category": "Oceanic"},
    "Samoa": {"flag": "ws", "category": "Oceanic"},
    "Tonga": {"flag": "to", "category": "Oceanic"},
    "Papua New Guinea": {"flag": "pg", "category": "Oceanic"}
}